config/routes.rb
Rails.application.routes.draw do
  resources :offices

  root to: "offices#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/office.rb
require 'net/http'
require 'json'

class Office < ApplicationRecord
  include Geokit::Geocoders
  acts_as_mappable :default_units => :miles,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :lat,
                   :lng_column_name => :lng

  validates :name, presence: true
  validates :lat, presence: true
  validates :lng, presence: true
  validates :address, presence: true
  validates :postcode, presence: true

  class << self
    def uri_postcode lat ,long
      #use of postcode.io to take postcode from latitude and longitude
      json_output = Office.request_api("http://api.postcodes.io/postcodes?lon=#{long}&lat=#{lat}")
      @postcode = Office.transform_json(json_output)
    end

    def uri_lat_long address
      #use of Geocoder to find latitude and longitude from an address
      @location = Geokit::Geocoders::MultiGeocoder.geocode (address)
      if @location.success
        @location
      end
    end

    def search postcode,radius
      if postcode && radius
        trans_poscode = postcode.gsub(/\s+/, "")
        postcode_full=Office.request_api("http://api.postcodes.io/postcodes/#{trans_poscode}")
        @home = [postcode_full[:result][:latitude],postcode_full[:result][:longitude]]
        Office.within(radius,:origin => @home).sort_by{|s| s.distance_to(@home)}
      else
        self.all
      end
    end

    def transform_json(json_input)
      json_input[:result][0][:postcode]
    end

    def request_api(url_input)
      url = url_input
      uri = URI(url)
      response = Net::HTTP.get(uri)
      JSON.parse(response).with_indifferent_access
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  before_action :set_office, only: [:show, :edit, :update, :destroy]
  before_action :set_api_params, only: [:create]
  before_action :set_postcode_params, only: [:create]
  # GET /offices
  # GET /offices.json
  def index
    @offices = Office.search(params[:search_postcode],params[:search_radius])
  end

  # GET /offices/1
  # GET /offices/1.json
  def show
  end

  # GET /offices/new
  def new
    @office = Office.new
  end

  # GET /offices/1/edit
  def edit
  end

  # POST /offices
  # POST /offices.json
  def create
    @office = Office.new(name: params[:office][:name],lat: @params_entry.lat,lng: @params_entry.lng,address: params[:office][:address], postcode: @params_postcode)
    respond_to do |format|
      if @office.save
        format.html { redirect_to offices_path, notice: 'Office was successfully created.' }
        format.json { render :show, status: :created, location: @office }
      else
        format.html { render :new }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offices/1
  # PATCH/PUT /offices/1.json
  def update
    respond_to do |format|
      if @office.update(office_params)
        format.html { redirect_to @office, notice: 'Office was successfully updated.' }
        format.json { render :show, status: :ok, location: @office }
      else
        format.html { render :edit }
        format.json { render json: @office.errors, status: :unprocessable_entity, notice: 'Your address is not valid' }
      end
    end
  end

  # DELETE /offices/1
  # DELETE /offices/1.json
  def destroy
    @office.destroy
    respond_to do |format|
      format.html { redirect_to offices_url, notice: 'Office was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_office
    @office = Office.find(params[:id])
  end

  def set_api_params
    @params_entry =Office.uri_lat_long(params[:office][:address])

  end
  def set_postcode_params
    if @params_entry && @params_entry.lat && @params_entry.lng
      @params_postcode = Office.uri_postcode(@params_entry.lat,@params_entry.lng)
    else
      flash[:notice] =  "Adress: #{params[:office][:address]} is not valid."
      redirect_to offices_path
    end
  end
  def office_params
    params.require(:office).permit(:name, :lat,:lng, :postcode,:address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geocodeuk</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/offices/_form.html.erb
<%= form_with(model: office, local: true) do |form| %>
    <% if office.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(office.errors.count, "error") %> prohibited this office from being saved:</h2>

          <ul>
            <% office.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, id: :office_name %>
    </div>

    <div class="field">
      <%= form.label :address %>
      <%= form.text_field :address %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

app/views/offices/edit.html.erb
<h1>Editing Office</h1>

<%= render 'form', office: @office %>

<%= link_to 'Show', @office %> |
<%= link_to 'Back', offices_path %>

app/views/offices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Offices</h1>

<%= form_tag offices_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search_postcode, params[:search_postcode] %>
      <%= text_field_tag :search_radius, params[:search_radius] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
<% end %>
<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Lat</th>
    <th>Long</th>
    <th>Address</th>
    <th>Postcode</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @offices.each do |office| %>
      <tr>
        <td><%= office.name %></td>
        <td><%= office.lat %></td>
        <td><%= office.lng %></td>
        <td><%= office.address %></td>
        <td><%= office.postcode %></td>
        <td><%= link_to 'Show', office %></td>
        <td><%= link_to 'Edit', edit_office_path(office) %></td>
        <td><%= link_to 'Destroy', office, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Office', new_office_path %>

app/views/offices/new.html.erb
<h1>New Office</h1>

<%= render 'form', office: @office %>

<%= link_to 'Back', offices_path %>

app/views/offices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @office.name %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @office.lat %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @office.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @office.long %>
</p>

<p>
  <strong>Long:</strong>
  <%= @office.long %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @office.postcode %>
</p>

<%= link_to 'Edit', edit_office_path(@office) %> |
<%= link_to 'Back', offices_path %>